<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2020 Sauce Labs. All Rights Reserved. T_5b767f</name>
   <tag></tag>
   <elementGuidId>78f22608-552f-40f9-92a3-bbf0268c99d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.footer_copy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='LinkedIn'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d348c45-f610-4df1-bc0c-4fd2397a6b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer_copy</value>
      <webElementGuid>e7469c41-57f7-46fa-b980-602c5155d21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>© 2020 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy</value>
      <webElementGuid>d18754ec-3b8f-442b-a123-5e2767ba412b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body&quot;]/footer[@class=&quot;footer&quot;]/div[@class=&quot;footer_copy&quot;]</value>
      <webElementGuid>79f8a8a6-81b8-43dd-adae-3af1f80287e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LinkedIn'])[1]/following::div[1]</value>
      <webElementGuid>081bbffb-30aa-46ac-860b-c0f53a56eb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::div[1]</value>
      <webElementGuid>9b91d4fb-32e4-4525-b812-edcfdfc24e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='© 2020 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy']/parent::*</value>
      <webElementGuid>501001ee-0f4b-4dbb-b90c-c61ad9bdda9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div</value>
      <webElementGuid>946a362f-d0c1-42e3-a147-76a09eb4fb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '© 2020 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy' or . = '© 2020 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy')]</value>
      <webElementGuid>c2f547c8-6d52-4220-9fab-d5e1512df920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
