<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Simple  an affordable price plans _841a56</name>
   <tag></tag>
   <elementGuidId>d7b293c0-a689-489f-9d97-a0329a7af809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='messagge']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#messagge</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>35379e8c-5d0c-418d-8dfb-0b87aa29b65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>messagge</value>
      <webElementGuid>eae2299e-afb3-44b9-b72a-3ec4d54517e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8677ed29-9bd8-4da2-99d0-f6bf003855d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-textarea</value>
      <webElementGuid>1d6eb7ac-ea27-4b2e-959e-c6170b7a0f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write something ...</value>
      <webElementGuid>007751f3-6b3e-46ec-9296-03104ba6f7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messagge&quot;)</value>
      <webElementGuid>4902b574-b3b5-4de5-8b60-c02f7e922134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='messagge']</value>
      <webElementGuid>1a257bdc-963c-48d9-8d6c-d82e979e67b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-complete']/textarea</value>
      <webElementGuid>afae1618-4909-420a-8f51-6e7660fa021b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9e8574db-f234-46c0-a203-fb5f6df5448d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'messagge' and @name = 'text' and @placeholder = 'Write something ...']</value>
      <webElementGuid>9b695ba1-dcbf-4faa-89b6-4374da25a146</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
