<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_DAFTAR</name>
   <tag></tag>
   <elementGuidId>2ce9c4cd-9160-401e-9f23-1f693863be12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.next-first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0c0a46f-eae6-46fa-8d90-2e77d9bcfb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>49860a7b-df27-47b3-b563-185928a15339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary next-first</value>
      <webElementGuid>0973488d-bc09-4c67-b0c2-0ebe18b08756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    DAFTAR
                </value>
      <webElementGuid>d6271407-d314-42f6-85d2-ef43a11e77a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerTalent&quot;)/div[@class=&quot;modal-dialog modal-dialog-scrollable minht boxIn&quot;]/div[@class=&quot;modal-content loadRegTalent&quot;]/div[@class=&quot;row inr&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;wrap-inquiry&quot;]/div[1]/a[@class=&quot;btn btn-primary next-first&quot;]</value>
      <webElementGuid>358cabd5-1e5f-4a6b-92a4-420e07df8cab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='submit'])[3]</value>
      <webElementGuid>b2600535-6718-4c4f-9589-00e6c0ee9965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registerTalent']/div/div/div/div/div/div/a[4]</value>
      <webElementGuid>328f9f91-e5f4-4527-9d86-085f1166412d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DAFTAR')]</value>
      <webElementGuid>b520f13c-c542-449c-96a3-ad351a3be44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan Daftar'])[1]/following::a[1]</value>
      <webElementGuid>3b6f2f6f-0cf0-4635-aa92-9c229c5c1dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[3]/following::a[2]</value>
      <webElementGuid>c2e72bc7-3d25-4b03-8e78-6aefe3f5d0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Pendaftaran Sudah Dicek'])[1]/preceding::a[1]</value>
      <webElementGuid>d2dd4f5d-b502-46d3-9c4a-b17a82b9002a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Form Pendaftaran?'])[1]/preceding::a[2]</value>
      <webElementGuid>c82e459c-c36e-4f12-903f-3c6b9062fd36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAFTAR']/parent::*</value>
      <webElementGuid>4227c281-12ec-4c90-acab-2c6328e2da9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>50bec55b-673c-4f49-847d-e13faeb32230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'submit' and (text() = '
                    DAFTAR
                ' or . = '
                    DAFTAR
                ')]</value>
      <webElementGuid>d93c39af-8149-4514-9225-a461bb88c0ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
