<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dari mana kamu dapat informasi soal k_9ca1e3</name>
   <tag></tag>
   <elementGuidId>a4baa196-60d4-4e68-be53-73a6e660d8ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refrensi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refrensi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18984bd5-4107-4cbd-a85f-dbf4282f3e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ccbb366-f908-4376-b2bf-d46c97e028a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>options</value>
      <webElementGuid>449def48-4849-4354-a721-0677d2797508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refrensi</value>
      <webElementGuid>0612cd10-2db6-49e3-ad76-368da02f6a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select w-25</value>
      <webElementGuid>ac66b6c8-0f68-40fc-8919-ed36677b3ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select or enter an option</value>
      <webElementGuid>4f3ff281-7a13-4c64-87b8-864d6f537579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refrensi</value>
      <webElementGuid>5997104d-3389-4fed-88bd-812505849f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refrensi&quot;)</value>
      <webElementGuid>14d8a709-4313-4023-8330-d8c12a5d25ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refrensi']</value>
      <webElementGuid>303955ff-9c16-44de-9c66-99ed7e9ccc86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register_main']/div[6]/div/div[2]/div/input</value>
      <webElementGuid>b38a4df5-6c68-4484-8c98-c1c02e8394f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/input</value>
      <webElementGuid>874c4404-2bf9-412c-9ce7-a9c72109919e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'refrensi' and @placeholder = 'Select or enter an option' and @name = 'refrensi']</value>
      <webElementGuid>d1966fa3-e7af-4282-beee-9af7f5cd0379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
