<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Email_email</name>
   <tag></tag>
   <elementGuidId>73cc97b1-cd2c-4b4c-ab0b-4741d7b3225c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register_main > div.form-group > div.row > div.col-md-8 > #Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Email'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48e2a05c-37b9-4d94-85bc-1fe2d946d932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e2ff7d75-e5f8-4518-bcc6-5fcbc74177f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5c7555c3-7bba-40ef-a96d-f21b16c293ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3b2a00ab-4a2c-4ead-926c-6147d9dd1ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>02d31b8e-d9c9-41e1-8271-668cac098d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Email</value>
      <webElementGuid>48a619f3-7fbb-4477-8d62-2225a1718727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_main&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/input[@id=&quot;Email&quot;]</value>
      <webElementGuid>1f4052a3-788c-4cc8-a71a-421ff34dd8dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Email'])[2]</value>
      <webElementGuid>e7bde4e3-80d0-41dc-8f57-ab421f1d84c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register_main']/div[2]/div/div[2]/input</value>
      <webElementGuid>40cbfffe-e258-490e-ab98-606cd14c9c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/form/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>560de23f-8cd1-4caa-a60c-965b70b2fb1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email' and @id = 'Email' and @placeholder = 'Your Email']</value>
      <webElementGuid>d4db1294-ccd1-41e6-accf-e0bb6a09edb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
