<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_navigation</name>
   <tag></tag>
   <elementGuidId>c6cd6662-459e-4dee-8671-b2c2aa5b39a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-border.btn-login.btn-xs.light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;$('.info').hide()&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>12624aca-9241-4801-ba3f-059d64ed0b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-border btn-login btn-xs light</value>
      <webElementGuid>104ffda1-563e-4050-b071-cb0776c9648e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#ModalLogin</value>
      <webElementGuid>78b24635-20c6-4be1-ad67-3c436db788e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>a3cc076d-5c57-4e06-a12d-a1b78781451c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('.info').hide()</value>
      <webElementGuid>23e4bedd-4b6e-4af0-96ad-73017734f51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>2201b967-5066-4bd7-a168-a03eaeeb2558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;menu-classic menu-fixed menu-one-page align-right menu-transparent light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;menu-cnt&quot;]/div[@class=&quot;menu-right&quot;]/div[@class=&quot;menu-custom-area&quot;]/a[@class=&quot;btn btn-border btn-login btn-xs light&quot;]</value>
      <webElementGuid>be2d30ff-f70d-4cd8-8823-16e0c5f0121c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;$('.info').hide()&quot;]</value>
      <webElementGuid>49c5a1d3-e31e-4fc9-98c7-ca5036dea4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>516c51c0-f59f-45e3-a8ac-ffdfbf1ac89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::a[1]</value>
      <webElementGuid>b0f4b3b9-849c-499c-a9f5-873fbf6a4eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/following::a[2]</value>
      <webElementGuid>2f1c7939-efaa-4a3d-80f6-8ee215e34af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::a[2]</value>
      <webElementGuid>a887e7eb-16c6-4507-aef0-0383b6f6ca18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[2]/div/div/a</value>
      <webElementGuid>1352b672-0e7d-4d82-a73a-668e448bd930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>7c767659-2e62-48ba-9848-4917e20077b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
