<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_daftar</name>
   <tag></tag>
   <elementGuidId>870c3eaf-6c8c-4e5b-a5ab-0024681c998b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@type='submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.next-first</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a234d37c-6035-44b5-bbaa-d667c492bfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ca4c5322-436d-4f16-a8d5-a00fa18c9e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary next-first</value>
      <webElementGuid>8d14348a-6d2b-4fc2-a142-39058ea4f798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    DAFTAR
                </value>
      <webElementGuid>bd63a14a-ef33-455b-b64f-13a18c5038ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerTalent&quot;)/div[@class=&quot;modal-dialog modal-dialog-scrollable minht boxIn&quot;]/div[@class=&quot;modal-content loadRegTalent&quot;]/div[@class=&quot;row inr&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;wrap-inquiry&quot;]/div[1]/a[@class=&quot;btn btn-primary next-first&quot;]</value>
      <webElementGuid>7412edfb-86c8-4946-a5eb-d148cbbda614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='submit'])[3]</value>
      <webElementGuid>e01a04cc-3e63-4303-9a4f-5020f91a7817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registerTalent']/div/div/div/div/div/div/a[4]</value>
      <webElementGuid>097e5bb6-f0d5-4374-add9-76f1e3b9c532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DAFTAR')]</value>
      <webElementGuid>5b657025-136f-41f8-b425-7d13d5fbf09a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan Daftar'])[1]/following::a[1]</value>
      <webElementGuid>7fbfb644-ff5d-4926-89e9-31e94bd87a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[3]/following::a[2]</value>
      <webElementGuid>2e40f45f-3726-4c36-b930-bca0c971ef13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Pendaftaran Sudah Dicek'])[1]/preceding::a[1]</value>
      <webElementGuid>61010372-2aed-457c-a572-3d9a91d6b7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Form Pendaftaran?'])[1]/preceding::a[2]</value>
      <webElementGuid>0448ed18-12cf-4913-ba35-4c119999d2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAFTAR']/parent::*</value>
      <webElementGuid>9a306ba2-45ad-4835-a1ec-e45e90dba060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>14153337-9f8d-445e-bb9f-09b0951e30b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'submit' and (text() = '
                    DAFTAR
                ' or . = '
                    DAFTAR
                ')]</value>
      <webElementGuid>7c077eca-9bad-45a9-9d2d-1860318c84b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
