<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dari mana kamu dapat informasi soal k_9ca1e3</name>
   <tag></tag>
   <elementGuidId>067de1b1-5410-4f1a-b3fb-8323f3779c25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refrensi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refrensi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3a22f47-400a-40b9-9b2b-8efe77207d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>250619d7-4f4d-48e2-8b85-5d85731f1466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>options</value>
      <webElementGuid>3a5582ce-1ce0-407b-923e-c42a22128eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refrensi</value>
      <webElementGuid>d9774eca-dd26-42c5-8aad-42d8bdee59ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select w-25</value>
      <webElementGuid>83912f5f-1e89-4f86-9c14-48840373ad82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select or enter an option</value>
      <webElementGuid>c8d1cd47-8976-465d-ac76-508c61d497fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refrensi</value>
      <webElementGuid>f12ac8b1-39ca-41d6-86f6-14e65456efa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refrensi&quot;)</value>
      <webElementGuid>21675c3b-c10d-4dc7-ba52-52be468aee5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refrensi']</value>
      <webElementGuid>11b83614-40f7-413b-ad4c-92bc35810cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register_main']/div[6]/div/div[2]/div/input</value>
      <webElementGuid>8151be14-946c-449e-b457-7aaaeccba5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/input</value>
      <webElementGuid>e353add8-e7bd-482d-be34-792978f94096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'refrensi' and @placeholder = 'Select or enter an option' and @name = 'refrensi']</value>
      <webElementGuid>5565c28d-681e-4701-ad61-c3e6caab5d9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
