<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login_navigation</name>
   <tag></tag>
   <elementGuidId>0dffd9e4-15ce-49f5-a192-4586543fc67e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;$('.info').hide()&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-border.btn-login.btn-xs.light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f46ca84-9cb8-405a-82a5-a702efbb395a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-border btn-login btn-xs light</value>
      <webElementGuid>edf438d1-c7a8-4f4c-80a1-b6c8d0a7a334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#ModalLogin</value>
      <webElementGuid>a980ec3f-5383-4f89-9140-81ededae1743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>71494581-9229-44ef-95ae-3156e0792a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$('.info').hide()</value>
      <webElementGuid>6c554805-d1db-48e8-9ff2-97516e09f40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>57659ec5-48ff-4db2-ac4d-c1e7e9e5c5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;menu-classic menu-fixed menu-one-page align-right menu-transparent light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;menu-cnt&quot;]/div[@class=&quot;menu-right&quot;]/div[@class=&quot;menu-custom-area&quot;]/a[@class=&quot;btn btn-border btn-login btn-xs light&quot;]</value>
      <webElementGuid>ae3931cc-4f93-460e-9bb4-7cbd4cba36d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;$('.info').hide()&quot;]</value>
      <webElementGuid>e49d5c2d-8987-4e50-ac72-bc4d673da780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>85707e80-c813-43e4-bb33-c98f538beb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::a[1]</value>
      <webElementGuid>00b88260-f963-49fc-b511-b3bae196679a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/following::a[2]</value>
      <webElementGuid>3e54c69b-565a-42fa-b0dd-3e6530b623f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::a[2]</value>
      <webElementGuid>95297f05-4e37-4d86-9c1a-2dc529585ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[2]/div/div/a</value>
      <webElementGuid>cd0b1b1c-1453-4e84-ac59-0a60595f258c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>8d58a263-2093-410c-a722-de81d42bffbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
