<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_phone_number</name>
   <tag></tag>
   <elementGuidId>b54e5dbf-7ba0-4366-ac83-27ef430f94ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='country_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#country_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8286a2de-01ec-473d-991a-919b16291e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>country_code</value>
      <webElementGuid>b150d05b-33ca-47a9-b1ba-1f5b872df11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select w-25</value>
      <webElementGuid>29b5cceb-2785-4cdb-a90e-b13806ab5164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>.form-select-lg example</value>
      <webElementGuid>65affabd-2294-4c9a-8ab3-1a22e7d02e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                    UK (+44)
                                                                                    Canada (+1)
                                                                                    Algeria (+213)
                                                                                    Andorra (+376)
                                                                                    Angola (+244)
                                                                                    Anguilla (+1264)
                                                                                    Antigua &amp; Barbuda (+1268)
                                                                                    Argentina (+54)
                                                                                    Armenia (+374)
                                                                                    Aruba (+297)
                                                                                    Australia (+61)
                                                                                    Austria (+43)
                                                                                    Azerbaijan (+994)
                                                                                    Bahamas (+1242)
                                                                                    Bahrain (+973)
                                                                                    Bangladesh (+880)
                                                                                    Barbados (+1246)
                                                                                    Belarus (+375)
                                                                                    Belgium (+32)
                                                                                    Belize (+501)
                                                                                    Benin (+229)
                                                                                    Bermuda (+1441)
                                                                                    Bhutan (+975)
                                                                                    Bolivia (+591)
                                                                                    Bosnia Herzegovina (+387)
                                                                                    Botswana (+267)
                                                                                    Brazil (+55)
                                                                                    Brunei (+673)
                                                                                    Bulgaria (+359)
                                                                                    Burkina Faso (+226)
                                                                                    Burundi (+257)
                                                                                    Cambodia (+855)
                                                                                    Cameroon (+237)
                                                                                    Cape Verde Islands (+238)
                                                                                    Cayman Islands (+1345)
                                                                                    Central African Republic (+236)
                                                                                    Chile (+56)
                                                                                    China (+86)
                                                                                    Colombia (+57)
                                                                                    Mayotte (+269)
                                                                                    Congo (+242)
                                                                                    Cook Islands (+682)
                                                                                    Costa Rica (+506)
                                                                                    Croatia (+385)
                                                                                    Cuba (+53)
                                                                                    Cyprus North (+90392)
                                                                                    Cyprus South (+357)
                                                                                    Czech Republic (+42)
                                                                                    Denmark (+45)
                                                                                    Djibouti (+253)
                                                                                    Dominican Republic (+1809)
                                                                                    Ecuador (+593)
                                                                                    Egypt (+20)
                                                                                    El Salvador (+503)
                                                                                    Equatorial Guinea (+240)
                                                                                    Eritrea (+291)
                                                                                    Estonia (+372)
                                                                                    Ethiopia (+251)
                                                                                    Falkland Islands (+500)
                                                                                    Faroe Islands (+298)
                                                                                    Fiji (+679)
                                                                                    Finland (+358)
                                                                                    France (+33)
                                                                                    French Guiana (+594)
                                                                                    French Polynesia (+689)
                                                                                    Gabon (+241)
                                                                                    Gambia (+220)
                                                                                    Georgia (+7880)
                                                                                    Germany (+49)
                                                                                    Ghana (+233)
                                                                                    Gibraltar (+350)
                                                                                    Greece (+30)
                                                                                    Greenland (+299)
                                                                                    Grenada (+1473)
                                                                                    Guadeloupe (+590)
                                                                                    Guam (+671)
                                                                                    Guatemala (+502)
                                                                                    Guinea (+224)
                                                                                    Guinea - Bissau (+245)
                                                                                    Guyana (+592)
                                                                                    Haiti (+509)
                                                                                    Honduras (+504)
                                                                                    Hong Kong (+852)
                                                                                    Hungary (+36)
                                                                                    Iceland (+354)
                                                                                    India (+91)
                                                                                    Indonesia (+62)
                                                                                    Iran (+98)
                                                                                    Iraq (+964)
                                                                                    Ireland (+353)
                                                                                    Israel (+972)
                                                                                    Italy (+39)
                                                                                    Jamaica (+1876)
                                                                                    Japan (+81)
                                                                                    Jordan (+962)
                                                                                    Uzbekistan (+7)
                                                                                    Kenya (+254)
                                                                                    Kiribati (+686)
                                                                                    Korea North (+850)
                                                                                    Korea South (+82)
                                                                                    Kuwait (+965)
                                                                                    Kyrgyzstan (+996)
                                                                                    Laos (+856)
                                                                                    Latvia (+371)
                                                                                    Lebanon (+961)
                                                                                    Lesotho (+266)
                                                                                    Liberia (+231)
                                                                                    Libya (+218)
                                                                                    Liechtenstein (+417)
                                                                                    Lithuania (+370)
                                                                                    Luxembourg (+352)
                                                                                    Macao (+853)
                                                                                    Macedonia (+389)
                                                                                    Madagascar (+261)
                                                                                    Malawi (+265)
                                                                                    Malaysia (+60)
                                                                                    Maldives (+960)
                                                                                    Mali (+223)
                                                                                    Malta (+356)
                                                                                    Marshall Islands (+692)
                                                                                    Martinique (+596)
                                                                                    Mauritania (+222)
                                                                                    Mexico (+52)
                                                                                    Micronesia (+691)
                                                                                    Moldova (+373)
                                                                                    Monaco (+377)
                                                                                    Mongolia (+976)
                                                                                    Montserrat (+1664)
                                                                                    Morocco (+212)
                                                                                    Mozambique (+258)
                                                                                    Myanmar (+95)
                                                                                    Namibia (+264)
                                                                                    Nauru (+674)
                                                                                    Nepal (+977)
                                                                                    Netherlands (+31)
                                                                                    New Caledonia (+687)
                                                                                    New Zealand (+64)
                                                                                    Nicaragua (+505)
                                                                                    Niger (+227)
                                                                                    Nigeria (+234)
                                                                                    Niue (+683)
                                                                                    Norfolk Islands (+672)
                                                                                    Northern Marianas (+670)
                                                                                    Norway (+47)
                                                                                    Oman (+968)
                                                                                    Palau (+680)
                                                                                    Panama (+507)
                                                                                    Papua New Guinea (+675)
                                                                                    Paraguay (+595)
                                                                                    Peru (+51)
                                                                                    Philippines (+63)
                                                                                    Poland (+48)
                                                                                    Portugal (+351)
                                                                                    Puerto Rico (+1787)
                                                                                    Qatar (+974)
                                                                                    Reunion (+262)
                                                                                    Romania (+40)
                                                                                    Rwanda (+250)
                                                                                    San Marino (+378)
                                                                                    Sao Tome &amp; Principe (+239)
                                                                                    Saudi Arabia (+966)
                                                                                    Senegal (+221)
                                                                                    Serbia (+381)
                                                                                    Seychelles (+248)
                                                                                    Sierra Leone (+232)
                                                                                    Singapore (+65)
                                                                                    Slovak Republic (+421)
                                                                                    Slovenia (+386)
                                                                                    Solomon Islands (+677)
                                                                                    Somalia (+252)
                                                                                    South Africa (+27)
                                                                                    Spain (+34)
                                                                                    Sri Lanka (+94)
                                                                                    St. Helena (+290)
                                                                                    St. Kitts (+1869)
                                                                                    St. Lucia (+1758)
                                                                                    Sudan (+249)
                                                                                    Suriname (+597)
                                                                                    Swaziland (+268)
                                                                                    Sweden (+46)
                                                                                    Switzerland (+41)
                                                                                    Syria (+963)
                                                                                    Taiwan (+886)
                                                                                    Thailand (+66)
                                                                                    Togo (+228)
                                                                                    Tonga (+676)
                                                                                    Trinidad &amp; Tobago (+1868)
                                                                                    Tunisia (+216)
                                                                                    Turkey (+90)
                                                                                    Turkmenistan (+993)
                                                                                    Turks &amp; Caicos Islands (+1649)
                                                                                    Tuvalu (+688)
                                                                                    Uganda (+256)
                                                                                    Ukraine (+380)
                                                                                    United Arab Emirates (+971)
                                                                                    Uruguay (+598)
                                                                                    Vanuatu (+678)
                                                                                    Vatican City (+379)
                                                                                    Venezuela (+58)
                                                                                    Virgin Islands - US (+1340)
                                                                                    Wallis &amp; Futuna (+681)
                                                                                    Yemen (North)(+969)
                                                                                    Yemen (South)(+967)
                                                                                    Zambia (+260)
                                                                                    Zimbabwe (+263)
                                                                            </value>
      <webElementGuid>58695f3b-e261-4669-bf50-b115beae650f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;country_code&quot;)</value>
      <webElementGuid>142e5daa-ee1a-4891-b11a-92e9fb7fcbb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='country_code']</value>
      <webElementGuid>35c524cc-efd0-493a-9686-929cf42ed233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register_main']/div[5]/div/div[2]/div/select</value>
      <webElementGuid>0a17b022-15e9-4940-890f-375f856a708a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon'])[1]/following::select[1]</value>
      <webElementGuid>9ca105c0-ce28-41c0-8e2d-09371382257c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harap isi Konfirmasi Password sama seperti Password'])[2]/following::select[1]</value>
      <webElementGuid>f65b1caa-a8f6-41df-989e-593186a54eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harap isi kolom nomor telepon!'])[1]/preceding::select[1]</value>
      <webElementGuid>8493f91b-34af-4e90-9467-b4686dc84863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon harus diantara 5 dan 15 angka'])[1]/preceding::select[1]</value>
      <webElementGuid>c1fd0e40-b65f-4335-bc83-c39cdc5ec2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>c5a820a3-abab-4bcf-8def-46233887100a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'country_code' and (text() = '
                                                                                    UK (+44)
                                                                                    Canada (+1)
                                                                                    Algeria (+213)
                                                                                    Andorra (+376)
                                                                                    Angola (+244)
                                                                                    Anguilla (+1264)
                                                                                    Antigua &amp; Barbuda (+1268)
                                                                                    Argentina (+54)
                                                                                    Armenia (+374)
                                                                                    Aruba (+297)
                                                                                    Australia (+61)
                                                                                    Austria (+43)
                                                                                    Azerbaijan (+994)
                                                                                    Bahamas (+1242)
                                                                                    Bahrain (+973)
                                                                                    Bangladesh (+880)
                                                                                    Barbados (+1246)
                                                                                    Belarus (+375)
                                                                                    Belgium (+32)
                                                                                    Belize (+501)
                                                                                    Benin (+229)
                                                                                    Bermuda (+1441)
                                                                                    Bhutan (+975)
                                                                                    Bolivia (+591)
                                                                                    Bosnia Herzegovina (+387)
                                                                                    Botswana (+267)
                                                                                    Brazil (+55)
                                                                                    Brunei (+673)
                                                                                    Bulgaria (+359)
                                                                                    Burkina Faso (+226)
                                                                                    Burundi (+257)
                                                                                    Cambodia (+855)
                                                                                    Cameroon (+237)
                                                                                    Cape Verde Islands (+238)
                                                                                    Cayman Islands (+1345)
                                                                                    Central African Republic (+236)
                                                                                    Chile (+56)
                                                                                    China (+86)
                                                                                    Colombia (+57)
                                                                                    Mayotte (+269)
                                                                                    Congo (+242)
                                                                                    Cook Islands (+682)
                                                                                    Costa Rica (+506)
                                                                                    Croatia (+385)
                                                                                    Cuba (+53)
                                                                                    Cyprus North (+90392)
                                                                                    Cyprus South (+357)
                                                                                    Czech Republic (+42)
                                                                                    Denmark (+45)
                                                                                    Djibouti (+253)
                                                                                    Dominican Republic (+1809)
                                                                                    Ecuador (+593)
                                                                                    Egypt (+20)
                                                                                    El Salvador (+503)
                                                                                    Equatorial Guinea (+240)
                                                                                    Eritrea (+291)
                                                                                    Estonia (+372)
                                                                                    Ethiopia (+251)
                                                                                    Falkland Islands (+500)
                                                                                    Faroe Islands (+298)
                                                                                    Fiji (+679)
                                                                                    Finland (+358)
                                                                                    France (+33)
                                                                                    French Guiana (+594)
                                                                                    French Polynesia (+689)
                                                                                    Gabon (+241)
                                                                                    Gambia (+220)
                                                                                    Georgia (+7880)
                                                                                    Germany (+49)
                                                                                    Ghana (+233)
                                                                                    Gibraltar (+350)
                                                                                    Greece (+30)
                                                                                    Greenland (+299)
                                                                                    Grenada (+1473)
                                                                                    Guadeloupe (+590)
                                                                                    Guam (+671)
                                                                                    Guatemala (+502)
                                                                                    Guinea (+224)
                                                                                    Guinea - Bissau (+245)
                                                                                    Guyana (+592)
                                                                                    Haiti (+509)
                                                                                    Honduras (+504)
                                                                                    Hong Kong (+852)
                                                                                    Hungary (+36)
                                                                                    Iceland (+354)
                                                                                    India (+91)
                                                                                    Indonesia (+62)
                                                                                    Iran (+98)
                                                                                    Iraq (+964)
                                                                                    Ireland (+353)
                                                                                    Israel (+972)
                                                                                    Italy (+39)
                                                                                    Jamaica (+1876)
                                                                                    Japan (+81)
                                                                                    Jordan (+962)
                                                                                    Uzbekistan (+7)
                                                                                    Kenya (+254)
                                                                                    Kiribati (+686)
                                                                                    Korea North (+850)
                                                                                    Korea South (+82)
                                                                                    Kuwait (+965)
                                                                                    Kyrgyzstan (+996)
                                                                                    Laos (+856)
                                                                                    Latvia (+371)
                                                                                    Lebanon (+961)
                                                                                    Lesotho (+266)
                                                                                    Liberia (+231)
                                                                                    Libya (+218)
                                                                                    Liechtenstein (+417)
                                                                                    Lithuania (+370)
                                                                                    Luxembourg (+352)
                                                                                    Macao (+853)
                                                                                    Macedonia (+389)
                                                                                    Madagascar (+261)
                                                                                    Malawi (+265)
                                                                                    Malaysia (+60)
                                                                                    Maldives (+960)
                                                                                    Mali (+223)
                                                                                    Malta (+356)
                                                                                    Marshall Islands (+692)
                                                                                    Martinique (+596)
                                                                                    Mauritania (+222)
                                                                                    Mexico (+52)
                                                                                    Micronesia (+691)
                                                                                    Moldova (+373)
                                                                                    Monaco (+377)
                                                                                    Mongolia (+976)
                                                                                    Montserrat (+1664)
                                                                                    Morocco (+212)
                                                                                    Mozambique (+258)
                                                                                    Myanmar (+95)
                                                                                    Namibia (+264)
                                                                                    Nauru (+674)
                                                                                    Nepal (+977)
                                                                                    Netherlands (+31)
                                                                                    New Caledonia (+687)
                                                                                    New Zealand (+64)
                                                                                    Nicaragua (+505)
                                                                                    Niger (+227)
                                                                                    Nigeria (+234)
                                                                                    Niue (+683)
                                                                                    Norfolk Islands (+672)
                                                                                    Northern Marianas (+670)
                                                                                    Norway (+47)
                                                                                    Oman (+968)
                                                                                    Palau (+680)
                                                                                    Panama (+507)
                                                                                    Papua New Guinea (+675)
                                                                                    Paraguay (+595)
                                                                                    Peru (+51)
                                                                                    Philippines (+63)
                                                                                    Poland (+48)
                                                                                    Portugal (+351)
                                                                                    Puerto Rico (+1787)
                                                                                    Qatar (+974)
                                                                                    Reunion (+262)
                                                                                    Romania (+40)
                                                                                    Rwanda (+250)
                                                                                    San Marino (+378)
                                                                                    Sao Tome &amp; Principe (+239)
                                                                                    Saudi Arabia (+966)
                                                                                    Senegal (+221)
                                                                                    Serbia (+381)
                                                                                    Seychelles (+248)
                                                                                    Sierra Leone (+232)
                                                                                    Singapore (+65)
                                                                                    Slovak Republic (+421)
                                                                                    Slovenia (+386)
                                                                                    Solomon Islands (+677)
                                                                                    Somalia (+252)
                                                                                    South Africa (+27)
                                                                                    Spain (+34)
                                                                                    Sri Lanka (+94)
                                                                                    St. Helena (+290)
                                                                                    St. Kitts (+1869)
                                                                                    St. Lucia (+1758)
                                                                                    Sudan (+249)
                                                                                    Suriname (+597)
                                                                                    Swaziland (+268)
                                                                                    Sweden (+46)
                                                                                    Switzerland (+41)
                                                                                    Syria (+963)
                                                                                    Taiwan (+886)
                                                                                    Thailand (+66)
                                                                                    Togo (+228)
                                                                                    Tonga (+676)
                                                                                    Trinidad &amp; Tobago (+1868)
                                                                                    Tunisia (+216)
                                                                                    Turkey (+90)
                                                                                    Turkmenistan (+993)
                                                                                    Turks &amp; Caicos Islands (+1649)
                                                                                    Tuvalu (+688)
                                                                                    Uganda (+256)
                                                                                    Ukraine (+380)
                                                                                    United Arab Emirates (+971)
                                                                                    Uruguay (+598)
                                                                                    Vanuatu (+678)
                                                                                    Vatican City (+379)
                                                                                    Venezuela (+58)
                                                                                    Virgin Islands - US (+1340)
                                                                                    Wallis &amp; Futuna (+681)
                                                                                    Yemen (North)(+969)
                                                                                    Yemen (South)(+967)
                                                                                    Zambia (+260)
                                                                                    Zimbabwe (+263)
                                                                            ' or . = '
                                                                                    UK (+44)
                                                                                    Canada (+1)
                                                                                    Algeria (+213)
                                                                                    Andorra (+376)
                                                                                    Angola (+244)
                                                                                    Anguilla (+1264)
                                                                                    Antigua &amp; Barbuda (+1268)
                                                                                    Argentina (+54)
                                                                                    Armenia (+374)
                                                                                    Aruba (+297)
                                                                                    Australia (+61)
                                                                                    Austria (+43)
                                                                                    Azerbaijan (+994)
                                                                                    Bahamas (+1242)
                                                                                    Bahrain (+973)
                                                                                    Bangladesh (+880)
                                                                                    Barbados (+1246)
                                                                                    Belarus (+375)
                                                                                    Belgium (+32)
                                                                                    Belize (+501)
                                                                                    Benin (+229)
                                                                                    Bermuda (+1441)
                                                                                    Bhutan (+975)
                                                                                    Bolivia (+591)
                                                                                    Bosnia Herzegovina (+387)
                                                                                    Botswana (+267)
                                                                                    Brazil (+55)
                                                                                    Brunei (+673)
                                                                                    Bulgaria (+359)
                                                                                    Burkina Faso (+226)
                                                                                    Burundi (+257)
                                                                                    Cambodia (+855)
                                                                                    Cameroon (+237)
                                                                                    Cape Verde Islands (+238)
                                                                                    Cayman Islands (+1345)
                                                                                    Central African Republic (+236)
                                                                                    Chile (+56)
                                                                                    China (+86)
                                                                                    Colombia (+57)
                                                                                    Mayotte (+269)
                                                                                    Congo (+242)
                                                                                    Cook Islands (+682)
                                                                                    Costa Rica (+506)
                                                                                    Croatia (+385)
                                                                                    Cuba (+53)
                                                                                    Cyprus North (+90392)
                                                                                    Cyprus South (+357)
                                                                                    Czech Republic (+42)
                                                                                    Denmark (+45)
                                                                                    Djibouti (+253)
                                                                                    Dominican Republic (+1809)
                                                                                    Ecuador (+593)
                                                                                    Egypt (+20)
                                                                                    El Salvador (+503)
                                                                                    Equatorial Guinea (+240)
                                                                                    Eritrea (+291)
                                                                                    Estonia (+372)
                                                                                    Ethiopia (+251)
                                                                                    Falkland Islands (+500)
                                                                                    Faroe Islands (+298)
                                                                                    Fiji (+679)
                                                                                    Finland (+358)
                                                                                    France (+33)
                                                                                    French Guiana (+594)
                                                                                    French Polynesia (+689)
                                                                                    Gabon (+241)
                                                                                    Gambia (+220)
                                                                                    Georgia (+7880)
                                                                                    Germany (+49)
                                                                                    Ghana (+233)
                                                                                    Gibraltar (+350)
                                                                                    Greece (+30)
                                                                                    Greenland (+299)
                                                                                    Grenada (+1473)
                                                                                    Guadeloupe (+590)
                                                                                    Guam (+671)
                                                                                    Guatemala (+502)
                                                                                    Guinea (+224)
                                                                                    Guinea - Bissau (+245)
                                                                                    Guyana (+592)
                                                                                    Haiti (+509)
                                                                                    Honduras (+504)
                                                                                    Hong Kong (+852)
                                                                                    Hungary (+36)
                                                                                    Iceland (+354)
                                                                                    India (+91)
                                                                                    Indonesia (+62)
                                                                                    Iran (+98)
                                                                                    Iraq (+964)
                                                                                    Ireland (+353)
                                                                                    Israel (+972)
                                                                                    Italy (+39)
                                                                                    Jamaica (+1876)
                                                                                    Japan (+81)
                                                                                    Jordan (+962)
                                                                                    Uzbekistan (+7)
                                                                                    Kenya (+254)
                                                                                    Kiribati (+686)
                                                                                    Korea North (+850)
                                                                                    Korea South (+82)
                                                                                    Kuwait (+965)
                                                                                    Kyrgyzstan (+996)
                                                                                    Laos (+856)
                                                                                    Latvia (+371)
                                                                                    Lebanon (+961)
                                                                                    Lesotho (+266)
                                                                                    Liberia (+231)
                                                                                    Libya (+218)
                                                                                    Liechtenstein (+417)
                                                                                    Lithuania (+370)
                                                                                    Luxembourg (+352)
                                                                                    Macao (+853)
                                                                                    Macedonia (+389)
                                                                                    Madagascar (+261)
                                                                                    Malawi (+265)
                                                                                    Malaysia (+60)
                                                                                    Maldives (+960)
                                                                                    Mali (+223)
                                                                                    Malta (+356)
                                                                                    Marshall Islands (+692)
                                                                                    Martinique (+596)
                                                                                    Mauritania (+222)
                                                                                    Mexico (+52)
                                                                                    Micronesia (+691)
                                                                                    Moldova (+373)
                                                                                    Monaco (+377)
                                                                                    Mongolia (+976)
                                                                                    Montserrat (+1664)
                                                                                    Morocco (+212)
                                                                                    Mozambique (+258)
                                                                                    Myanmar (+95)
                                                                                    Namibia (+264)
                                                                                    Nauru (+674)
                                                                                    Nepal (+977)
                                                                                    Netherlands (+31)
                                                                                    New Caledonia (+687)
                                                                                    New Zealand (+64)
                                                                                    Nicaragua (+505)
                                                                                    Niger (+227)
                                                                                    Nigeria (+234)
                                                                                    Niue (+683)
                                                                                    Norfolk Islands (+672)
                                                                                    Northern Marianas (+670)
                                                                                    Norway (+47)
                                                                                    Oman (+968)
                                                                                    Palau (+680)
                                                                                    Panama (+507)
                                                                                    Papua New Guinea (+675)
                                                                                    Paraguay (+595)
                                                                                    Peru (+51)
                                                                                    Philippines (+63)
                                                                                    Poland (+48)
                                                                                    Portugal (+351)
                                                                                    Puerto Rico (+1787)
                                                                                    Qatar (+974)
                                                                                    Reunion (+262)
                                                                                    Romania (+40)
                                                                                    Rwanda (+250)
                                                                                    San Marino (+378)
                                                                                    Sao Tome &amp; Principe (+239)
                                                                                    Saudi Arabia (+966)
                                                                                    Senegal (+221)
                                                                                    Serbia (+381)
                                                                                    Seychelles (+248)
                                                                                    Sierra Leone (+232)
                                                                                    Singapore (+65)
                                                                                    Slovak Republic (+421)
                                                                                    Slovenia (+386)
                                                                                    Solomon Islands (+677)
                                                                                    Somalia (+252)
                                                                                    South Africa (+27)
                                                                                    Spain (+34)
                                                                                    Sri Lanka (+94)
                                                                                    St. Helena (+290)
                                                                                    St. Kitts (+1869)
                                                                                    St. Lucia (+1758)
                                                                                    Sudan (+249)
                                                                                    Suriname (+597)
                                                                                    Swaziland (+268)
                                                                                    Sweden (+46)
                                                                                    Switzerland (+41)
                                                                                    Syria (+963)
                                                                                    Taiwan (+886)
                                                                                    Thailand (+66)
                                                                                    Togo (+228)
                                                                                    Tonga (+676)
                                                                                    Trinidad &amp; Tobago (+1868)
                                                                                    Tunisia (+216)
                                                                                    Turkey (+90)
                                                                                    Turkmenistan (+993)
                                                                                    Turks &amp; Caicos Islands (+1649)
                                                                                    Tuvalu (+688)
                                                                                    Uganda (+256)
                                                                                    Ukraine (+380)
                                                                                    United Arab Emirates (+971)
                                                                                    Uruguay (+598)
                                                                                    Vanuatu (+678)
                                                                                    Vatican City (+379)
                                                                                    Venezuela (+58)
                                                                                    Virgin Islands - US (+1340)
                                                                                    Wallis &amp; Futuna (+681)
                                                                                    Yemen (North)(+969)
                                                                                    Yemen (South)(+967)
                                                                                    Zambia (+260)
                                                                                    Zimbabwe (+263)
                                                                            ')]</value>
      <webElementGuid>1af2192e-7890-4aac-abb5-dac9cd17c61e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
